---
- hosts: em-ansible-host
  tasks:
  - name: deploy pdb
    uri:
      url: https://osc-em13.oda.aus.osc:7802{{ lookup('file', '/tmp/output_dbaas_pdb_template_uri.txt') }}
      method: POST
      headers:
        Content-Type: "application/oracle.com.cloud.common.PluggableDbPlatformInstance+json"
        Accept: "application/oracle.com.cloud.common.PluggableDbPlatformInstance+json"
      return_content: yes
      user: osc_anz_admin
      password: welcome1
      validate_certs: no
      force_basic_auth: yes
      body_format: json 
      body: {
        "zone" : "/em/cloud/dbaas/zone/0129A72DB32D4199B59ABFA64085EAB3",
        "name" : "Request for an Empty PDB BA",
        "params" : {
          "username" : "TestUser",
          "password" : "welcome1",
          "workload_name": "Small",
          "pdb_name" : "BoAPDB1",
          "service_name" : "BoAPDB1_Service" ,
          "tablespaces" : [ "pdb_tbs1" ] 
        },
       "instance_target_properties": [ { "name": "Department", "value": "Development" } ]
      }
    register: deploy_pdb
  - name: show pdb deployment status
    #debug: var=deploy_pdb
    #debug: msg="{{ deploy_pdb.json | to_nice_json(indent=5) }}"
    debug: 
      msg: "{{ deploy_pdb.content }}"

  - name: copy result
    copy:
      content: >
        "{{ deploy_pdb.content }}"
      dest: "/tmp/output_dbaas_deploy_pdb.txt"

  - name: create request id file
    shell:
      /bin/grep pluggable /tmp/output_dbaas_deploy_pdb.txt|grep uri|/usr/bin/awk '{print $3}'|/usr/bin/sed 's/\"//g'|/usr/bin/sed 's/\,//g' > /tmp/output_dbaas_deploy_pdb_id.txt;
      dockerimg=`/usr/bin/docker ps | /usr/bin/grep nci-ansible-ui | /usr/bin/awk '{print $1}'`;
      /usr/bin/docker cp /tmp/output_dbaas_deploy_pdb_id.txt ${dockerimg}:/tmp/;
    args:
      executable: /bin/bash
