---
- hosts: em-ansible-host
  tasks:
  - name: get pdb template
    uri:
      url: https://osc-em13.oda.aus.osc:7802/em/cloud?service_templates
      method: GET
      header:
        Accept: application/json
      return_content: yes
      user: osc_anz_admin
      password: welcome1
      validate_certs: no
      force_basic_auth: yes
      body_format: json 
    register: pdb_template
  - name: show list
    #debug: var=pdb_template
    #debug: msg="{{ pdb_template.json | to_nice_json(indent=5) }}"
    debug: 
      msg: "{{ pdb_template.content }}"

  - name: copy output
    copy:
      content: >
        "{{ pdb_template.content }}"
      dest: "/tmp/output_dbaas_pdb_template.txt"

  - name: create pdb template uri file
    shell:
      /bin/grep pluggable /tmp/output_dbaas_pdb_template.txt|grep uri|/usr/bin/awk '{print $3}'|/usr/bin/sed 's/\"//g'|/usr/bin/sed 's/\,//g' > /tmp/output_dbaas_pdb_template_uri.txt;
      dockerimg=`/usr/bin/docker ps | /usr/bin/grep nci-ansible-ui | /usr/bin/awk '{print $1}'`;
      /usr/bin/docker cp /tmp/output_dbaas_pdb_template_uri.txt ${dockerimg}:/tmp/;
    args:
      executable: /bin/bash
