---
- hosts: em-ansible-host
  tasks:
  - name: get pdb template
    uri:
      url: https://osc-em13.oda.aus.osc:7802{{ lookup('file', '/tmp/output_dbaas_deploy_pdb_id.txt') }}
      method: POST
      headers:
        Content-Type: "application/oracle.com.cloud.common.PluggableDbPlatformInstance+json"
        Accept: "application/oracle.com.cloud.common.PluggableDbPlatformInstance+json"
      return_content: yes
      user: osc_anz_admin
      password: welcome1
      validate_certs: no
      force_basic_auth: yes
      body_format: json 
      body: {"operation": "SHUTDOWN"}
    register: shutdown_pdb
  - name: show list
    #debug: var=shutdown_pdb
    #debug: msg="{{ shutdown_pdb.json | to_nice_json(indent=5) }}"
    debug: 
      msg: "{{ shutdown_pdb.content }}"
