---
- hosts: ovmm-ansible-host
  tasks:
  - name: deploy vm from assembly vm
    uri:
      url: https://ovmm-test.gdn.aus.osc:7002/ovm/core/wsapi/rest/AssemblyVm/11d02c93cd_vm_OVM_OL6U8_x86_64_PVM1/createVm
      method: PUT
      return_content: yes
      headers: 
        Content-Type: "application/json"
        Accept: "application/json"
      user: admin
      password: Welcome1
      validate_certs: no
      force_basic_auth: yes
      body: {}
      body_format: json 
      status_code: 201
    register: output_deploy_assemblyVm
  - name: show vm deploy status
    debug: var=output_deploy_assemblyVm.json
    #debug: msg="{{ var=output_deploy_assemblyVm | to_nice_json(indent=5) }}"

  - name: copy output
    copy:
      content: >
        "{{ output_deploy_assemblyVm.json | to_nice_json() }}"
      dest: "/tmp/output_ovmm_deploy_assemblyVm.txt"

  - name: search deployment id
    shell:
      /bin/grep value /tmp/output_ovmm_deploy_assemblyVm.txt | /usr/bin/awk '{print $2}'| /usr/bin/sed 's/\"//g' > /tmp/output_ovmm_jobid.txt;
      dockerimg=`/usr/bin/docker ps | /usr/bin/grep nci-ansible-ui | /usr/bin/awk '{print $1}'`;
      /usr/bin/docker cp /tmp/output_ovmm_jobid.txt ${dockerimg}:/tmp/ ;
    args:
      executable: /bin/bash
