---
- hosts: ovmm-ansible-host
  tasks:
  - name: show vm  details 
    vars:
      contents: "{{ lookup('file', '/tmp/output_ovmm_vmid.txt') }}"

    uri:
      url: https://ovmm-test.gdn.aus.osc:7002/ovm/core/wsapi/rest/Vm/{{ contents }}
      method: GET
      headers: 
        Content-Type: "application/json"
        Accept: "application/json"
      return_content: yes
      user: admin
      password: Welcome1
      validate_certs: no
      force_basic_auth: yes
      body_format: json 
    register: lookupvmdetails
  - name: show list
    debug: var=lookupvmdetails.json

  - name: vnic vm id
    copy:
      content: >
        "{{ lookupvmdetails.json.virtualNicIds | to_nice_json() }}"
      dest: "/tmp/output_ovmm_vnic_org.txt"

  - name: search vnic id
    shell:
      /usr/bin/grep value /tmp/output_ovmm_vnic_org.txt | /usr/bin/awk '{print $2}' | /usr/bin/sed 's/\"//g' > /tmp/output_ovmm_vnicid.txt;
      dockerimg=`/usr/bin/docker ps | /usr/bin/grep nci-ansible-ui | /usr/bin/awk '{print $1}'`;
      /usr/bin/docker cp /tmp/output_ovmm_vnicid.txt ${dockerimg}:/tmp/ ;
    args:
      executable: /bin/bash



