---
- hosts: em-ansible-host
  tasks:
  - name: start vm
    vars:
      contents: "{{ lookup('file', '/tmp/output_vm_uri.txt') }}"

    uri:
      url: https://em13-test.gdn.aus.osc:7803{{ contents }}
      method: PUT
      return_content: yes
      headers: 
        Content-Type: application/oracle.com.cloud.common.VM+json
      user: osc_anz_admin
      password: welcome1
      validate_certs: no
      force_basic_auth: yes
      body: {"status":"STARTED"}

      body_format: json 
    register: output_start_vm
  - name: output start vm
    #detail output
    debug: var=output_start_vm.content
